/**
 * Represents a log entry for an action performed by the orchestrator.
 */
export type TActionLog = {
  source: string;
  timestamp: number;
  message: string;
};

/**
 * The result of performing an action.
 * @template TStatus - The type of the orchestrator's status.
 * @template TMemory - The type of the orchestrator's memory/state.
 * @property status - Optional next status returned by the action.
 * @property memory - Optional partial update to the orchestrator's memory.
 */
export type TActionResult<TStatus, TMemory> = {
  status?: TStatus;
  memory?: Partial<TMemory>;
};

/**
 * Function signature for executing an action.
 * @template TStatus - The type representing possible statuses.
 * @template TMemory - The type representing the memory/state object.
 * @param status - The current status before the action.
 * @param memory - The current memory/state before the action.
 * @returns An action result, possibly asynchronous, containing next status and memory updates.
 */
export type TActionExecutor<TStatus extends string | number, TMemory> = (
  status: TStatus,
  memory: Partial<TMemory>,
) => TActionResult<TStatus, TMemory> | Promise<TActionResult<TStatus, TMemory>>;

/**
 * Represents an executable action within the orchestrator workflow.
 * Handles execution logic, status/memory updates, and log generation.
 *
 * @template TStatus - The type representing possible statuses.
 * @template TMemory - The type representing the memory/state object.
 */
export class Action<TStatus extends string | number, TMemory> {
  private readonly _key: string;
  private readonly _execute: TActionExecutor<TStatus, TMemory>;
  private readonly _generateLog: () => string;
  private _log?: TActionLog;

  constructor(params: {
    key: string;
    execute: TActionExecutor<TStatus, TMemory>;
    generateLog: () => string;
  }) {
    this._key = params.key;
    this._execute = params.execute;
    this._generateLog = params.generateLog;
  }

  /**
   * Gets the unique key for this action.
   */
  get key(): string {
    return this._key;
  }

  /**
   * Gets the most recent log generated by this action, if any.
   */
  get log(): TActionLog | undefined {
    return this._log;
  }

  /**
   * Performs this action with the given status and memory.
   * Produces optional next status and memory updates, and generates a log.
   * @param status - The current status before the action.
   * @param memory - The current memory/state before the action.
   * @returns A promise resolving to the action result (next status, memory update).
   */
  async perform(
    status: TStatus,
    memory: Partial<TMemory>,
  ): Promise<TActionResult<TStatus, TMemory>> {
    const result = await this._execute(status, memory);

    this._log = {
      source: this._key,
      timestamp: Date.now(),
      message: this._generateLog(),
    };

    return result;
  }
}
